---
controller:
  appprotect:
    enable: true
  appprotectdos:
    enable: true
  enableSnippets: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
    tag: latest
    pullPolicy: Always
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred 
prometheus:
  create: true
